/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "square.h"


void square_prog_1(char *host)
{
	CLIENT *clnt;
	square_out  *result_1;
	square_in  squareproc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SQUARE_PROG, SQUARE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = squareproc_1(&squareproc_1_arg, clnt);
	if (result_1 == (square_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[]) {
	char *host;
	CLIENT *cl; square_in in; square_out *out;

	if (argc != 3) {
		printf("client <localhost> <integer>");
		// printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	cl = clnt_create (argv[1], SQUARE_PROG, SQUARE_VERS, "tcp");

	in.arg1 = atol (argv [2]);
	if ((out = squareproc_1(&in, cl)) == NULL){
		printf ("Error"); 
		exit(1);
	}
	printf ("Result %ld\n", out -> res1); 
	exit(0);

	// host = argv[1];
	// square_prog_1 (host);

}
